# Generated by Django 5.1.6 on 2025-02-18 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=255)),
                ('prioridade', models.CharField(choices=[('baixa', 'baixa'), ('media', 'media'), ('alta', 'alta')], max_length=5)),
                ('data_cadastro', models.DateField()),
                ('status', models.CharField(choices=[('a fazer', 'a fazer'), ('fazendo', 'fazendo'), ('pronto', 'pronto')], max_length=7)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.usuario')),
            ],
            options={
                'db_table': 'tarefa',
            },
        ),
    ]
