# Generated by Django 4.2.20 on 2025-03-31 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_tarefa_options_alter_usuario_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tarefa",
            options={},
        ),
        migrations.AlterModelOptions(
            name="usuario",
            options={},
        ),
    ]
